export * from "./common.routes"
export * from "./auth.routes"
export * from "./product.routes"
export * from "./shop.routes"
export * from "./category.routes"
export * from "./size.routes"
export * from "./color.routes"
